### ISSUE TITLE
Add tests for commands.go

### ISSUE THREAD

**Issue by cristaloleg** [cristalhq/zookeeper#1]
Currently we've 3 operations called `CallSrvr`, `CallRuok ` and `CallCons `.

Adding simple unit tests to check that each regex parses output correctly should be enough.

There is no need to start a Zookeeper server.

**Comment by edenriquez** [comment]
@cristaloleg can I take this? 
If so, Can you give me and input for every command ? or give me an example how to run the project ?.
Thanks!

**Comment by tetafro** [comment]
@edenriquez sorry, I should have said that I'd already started :(

**Comment by cristaloleg** [comment]
@edenriquez you may use this page to run ZK locally https://zookeeper.apache.org/doc/r3.1.2/zookeeperStarted.html

And if you're interested in ZK client you may implement few things from https://github.com/cristalhq/zookeeper/issues/2
